// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oobxytqzbnvtspodjjop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vYnh5dHF6Ym52dHNwb2Rqam9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMwMzQwNTUsImV4cCI6MjA3ODYxMDA1NX0.EirF0I3Bhmwo5PUDPL3IcyBwjNQPhO14r3zttm6JU88";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {
      'x-client-info': 'lovable-keyword-research'
    }
  }
});
